### ISSUE TITLE
errors when checking lists and matrices

### ISSUE THREAD

**Issue by kerschke** [mllg/checkmate#63]
There seems to be a bug in `expect_matrix` and `expect_list`. At least, I can't check for matrices since updating to the current developers version.

```{r}
> m = matrix(1:6, ncol = 3)
> expect_matrix(m)
Error in testthat::expectation(identical(res, TRUE), failure_msg = res,  : 
unused arguments (failure_msg = res, success_msg = "all good")
>
> mylist = list(a = 2, b = c("hello", "world"))
> expect_list(mylist)
Error in testthat::expectation(identical(res, TRUE), failure_msg = res,  : 
  unused arguments (failure_msg = res, success_msg = "all good")
```

**Comment by kerschke** [comment]
Apparently, this is caused by the update of `testthat::expectation`. In the current version on CRAN, that function looks like this:
```{r}
#' @param passed a single logical value indicating whether the test passed
#'  (\code{TRUE}), failed (\code{FALSE}), or threw an error (\code{NA})
#' @param failure_msg A text description of failure
#' @param success_msg A text description of success
#' @param srcref Source reference, if known
#' @keywords internal
#' @export
expectation <- function(passed, failure_msg, success_msg = "unknown", srcref = NULL) {
  structure(
    list(
      passed = passed,
      error = FALSE,
      skipped = FALSE,
      failure_msg = failure_msg,
      success_msg = success_msg,
      srcref = srcref
    ),
    class = "expectation"
  )
}
```

However, hadley changed the API of that function on github and plans to release it soon:

```{r}
#' @param passed a single logical value indicating whether the test passed
#'  (\code{TRUE}), failed (\code{FALSE}), or threw an error (\code{NA})
#' @param message A text description of failure
#' @param srcref Source reference, if known
#' @keywords internal
#' @export
expectation <- function(type, message, srcref = NULL) {
  type <- match.arg(type, c("success", "failure", "error", "skip", "warning"))

  structure(
    list(
      message = message,
      srcref = srcref
    ),
    class = c(
      paste0("expectation_", type),
      "expectation",
      "condition"
    )
  )
}
```

**Comment by mllg** [comment]
Good catch. I'll release a new checkmate version right after the testthat upgrade. If you want to help out, you can try if the testthat branch works for you.

**Comment by kerschke** [comment]
Well.. at least the tests work now. Unfortunately, building/installing the package now fails locally :-/
```
* checking whether package ‘flacco’ can be installed ... ERROR
Installation failed.
See ‘/Users/Pascal/Documents/repos/pkgs/flacco.Rcheck/00install.out’ for details.
```
On the other hand it seems to work on travis, but codecov and coverall now miss a lot of unit tests (for whatever reason). Is it possible that they actually load the cran-versions of testthat and checkmate and thus have some problems with the tests? Otherwise, I have no idea what's causing that behaviour.. Do you?

**Comment by mllg** [comment]
Should work after you upgrade to the new testthat.
```r
devtools::install_github("hadley/testthat")
```
I'll upload checkmate ASAP after the testthat upload. In principle you can leave flacco as-is on CRAN.

**Comment by kerschke** [comment]
I already did upgrade `testthat` and `checkmate` locally. That's why I am surprised that it's not working..

**Comment by kerschke** [comment]
Since the unit tests work locally and on travis (but not on coverall), I guess you're right that I could leave flacco as-is on CRAN. Probably the problem will disappear once testthat and checkmate are updated on CRAN.
Thus, I'll close the issue for now. Thanks for the quick help :-)

**Comment by mllg** [comment]
Well, that's strange. The package should now be compatible with the current and upcoming testthat, maybe this is now resolved.

**Comment by kerschke** [comment]
I just made a pull of your most recent commit to checkmate - but still receive the same error. Could you check, if you also get that error when running rcheck on flacco?

**Comment by mllg** [comment]
With the current GH versions of flacco and checkmate, respectively:

* `rtest` works with testthat (cran and devel)
* `rcheck` -> after uncommenting the if-stuff in `tests/test-*.R`: all OK and tests running with testthat (cran and devel)

Do you have multiple libraries on your system? 
```r
x = table(rownames(installed.packages()))
x[x >= 2]
```
Any relevant package in this output?

**Comment by kerschke** [comment]
Ah ok.. Your guess was right - apparently I had packages in multiple libraries. Thanks for solving that issue :-)
